### ISSUE TITLE
Multiple test object from the same parquet file

### ISSUE THREAD

**Issue by artlbv** [cms-l1-dpg/Phase2-L1MenuTools#6]
In the current (C++) fwk there are cases in which multiple test objects are derived from the same collection. For example, `tkElectron` and `tkElectronIso` in our jargon would be defined as:
```
  test_objects:
    tkElectron:
      suffix: "Pt"
      label: "TkElectron"
      cuts:
        - "abs({eta}) < 2.4"
        - "{passesloosetrackid} == 1"
    tkElectronIso:
      suffix: "Pt"
      label: "TkElectron Iso"
      iso_BB: 0.13
      iso_EE: 0.28
      iso_branch: "trkiso"
      quality_id: "QUAL_BarrelNoneEndcap3"
      cuts:
        - "abs({eta}) < 2.4"
```
But the code cannot handle this situation, because it tries to look for `V22_DY_tkElectronIso.parquet` file, which does not exist. Both these objects (`tkElectron` and `tkElectronIso` in fact should be loaded from the same file: `V22_DY_tkElectron.parquet`).
